### ISSUE TITLE
`pre-commit` not use packages in Python env

### ISSUE THREAD

**Issue by edxu96** [pasty-dev/cmdict#85]
Maybe avoid using `pre-commit` in GitHub Actions, but use `black`, `darglint`, `flake8`, etc directly via command line.

Actually, the file, `.pre-commit-config.yaml` right now seems to install different versions of packages than those in `pyproject.toml`. For example, the stable version of `black` will be installed, because:

```
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
```

 versus the 19.10b0 version in `pyproject.toml`.

Even if I changed `.pre-commit-config.yaml` to:

```yaml
default_language_version:
    python: python3.6

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-docstring-first
    - id: check-toml
    - id: check-yaml
    - id: trailing-whitespace

-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      additional_dependencies:
          - 'flake8-builtins'
          - 'flake8-docstrings'
          - 'flake8-import-order'
          - 'pycodestyle'
          - 'pydocstyle'

-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.4.1
    hooks:
    - id: darglint
```

Another problem in the next comment happens.
